---
settings:
  name: Amazon FSx for NetApp ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de Amazon FSX para ONTAP de NetApp
    url: "/index.html"
  - title: Notas de la versión
    url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Obtenga más información sobre Amazon FSX para ONTAP de NetApp
      url: "/start/concept-fsx-aws.html"
    - title: Inicio rápido
      url: "/start/task-getting-started-fsx.html"
    - title: Configure los permisos
      url: "/requirements/task-setting-up-permissions-fsx.html"
    - title: Crear o detectar un entorno de trabajo
      url: "/use/task-creating-fsx-working-environment.html"
  - title: Gestionar un sistema de archivos FSx for ONTAP
    url: "/use/task-manage-working-environment.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/support/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/support/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
