= Asocie FSX para el sistema de archivos ONTAP a un espacio de trabajo en BlueXP 
:allow-uri-read: 




=== Asocie FSX para el sistema de archivos ONTAP a un espacio de trabajo en BlueXP 

Después de la integración de BlueXP  en noviembre de 2024, los sistemas de archivos FSx para ONTAP recién creados no se asociaron a un espacio de trabajo en BlueXP . Ahora, cuando creas o detectas sistemas de archivos FSx for ONTAP, estos se asocian a un espacio de trabajo dentro de una cuenta de BlueXP .

Si ya tienes sistemas de archivos FSx para ONTAP que no están asociados a un espacio de trabajo, te ayudaremos a asociarlos a un espacio de trabajo en BlueXP . link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-get-help.html#create-a-case-with-netapp-support["Cree un caso con el soporte de NetApp"^]Puede hacerlo desde la consola de BlueXP . Seleccione *Workload Factory* como servicio.



=== Eliminación del sistema de archivos del lienzo de BlueXP 

Ahora puede eliminar un sistema de archivos FSx para ONTAP de un espacio de trabajo en el lienzo de BlueXP . Esta operación disocia el sistema de archivos de un espacio de trabajo para que pueda asociarlo a otro espacio de trabajo dentro de la misma cuenta de BlueXP .

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-remove-filesystem.html["Aprende a eliminar un sistema de archivos FSx para ONTAP de un espacio de trabajo en BlueXP "^]



=== Rastreador disponible para operaciones de monitoreo y seguimiento

Tracker, una nueva funcionalidad de supervisión, está disponible en Amazon FSx para NetApp ONTAP de BlueXP . Puede utilizar Tracker para supervisar y realizar un seguimiento del progreso y el estado de las credenciales, el almacenamiento y las operaciones de enlace, revisar detalles de tareas de operación y subtareas, diagnosticar cualquier problema o fallo, editar parámetros para operaciones fallidas y volver a intentar operaciones fallidas.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["Aprende a supervisar y hacer un seguimiento de las operaciones de FSx para ONTAP en BlueXP "^]



=== CloudShell disponible en cargas de trabajo de BlueXP 

CloudShell está disponible cuando estás en cargas de trabajo de BlueXP  dentro de la consola de BlueXP . CloudShell le permite usar las credenciales de AWS y ONTAP que ha proporcionado en su cuenta de BlueXP  y ejecutar comandos de la CLI de AWS o comandos de la CLI de ONTAP en un entorno similar al shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Usar CloudShell"^]
