---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager 
summary: FSX de Amazon para ONTAP de NetApp es un servicio completamente gestionado que permite a los clientes lanzar y ejecutar sistemas de archivos con el sistema operativo de almacenamiento ONTAP de NetApp. FSX para ONTAP proporciona las mismas funciones, rendimiento y funcionalidades administrativas que los clientes de NetApp utilizan actualmente en las instalaciones, con la simplicidad, agilidad, seguridad y escalabilidad de un servicio de AWS nativo. 
---
= Obtenga más información sobre Amazon FSX para ONTAP de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX para ONTAP de NetApp"^] Es un servicio totalmente gestionado que permite a los clientes iniciar y ejecutar sistemas de archivos con tecnología del sistema operativo de almacenamiento NetApp ONTAP. FSX para ONTAP proporciona las mismas funciones, rendimiento y funcionalidades administrativas que los clientes de NetApp utilizan en las instalaciones, con la simplicidad, agilidad, seguridad y escalabilidad de un servicio de AWS nativo.



== Funciones

* No es necesario configurar ni gestionar dispositivos de almacenamiento, software o backups.
* Compatibilidad con los protocolos CIFS, NFSv3, NFSv4.x y SMB v2.0: V3.1.1.
* Capacidad de almacenamiento de datos prácticamente ilimitada y de bajo coste mediante el uso del nivel de almacenamiento a el que se accede con poca frecuencia (IA).
* Certificado para ejecutarse en aplicaciones sensibles a la latencia, incluido Oracle RAC.
* Opción de precios incluidos y de pago por uso.




== Características adicionales en BlueXP

* FSX para ONTAP es compatible cuando se utiliza BlueXP en modo _standard_ o _restricted_.
+
** El modo estándar hace uso de la capa SaaS de BlueXP para proporcionar una funcionalidad completa.
** El modo restringido está disponible para organizaciones que tienen restricciones de conectividad.
+
Consulte link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Modos de implementación de BlueXP"^] si quiere más información.



* Uso link:https://docs.netapp.com/us-en/bluexp-family/["BlueXP"^] Además, con un conector en AWS, puedes crear y gestionar volúmenes, replicar datos e integrar FSx para ONTAP con los servicios de nube de NetApp, como la clasificación de BlueXP y la copia y sincronización de BlueXP.
* Con la tecnología impulsada por la inteligencia artificial (IA), la clasificación de BlueXP puede ayudarte a comprender el contexto de los datos e identificar los datos confidenciales que residen en tus cuentas de FSx para ONTAP. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Leer más"^].
* Con la copia y sincronización de BlueXP, podrá automatizar la migración de datos a cualquier destino en la nube u on-premises. https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["Leer más"^]




== Coste

Su cuenta FSX para ONTAP es mantenida por AWS y no por BlueXP. Consulte https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Guía de inicio de Amazon FSX para ONTAP de NetApp"^].

Hay un coste adicional asociado al uso del conector en AWS y a servicios de datos opcionales, como la copia y sincronización de BlueXP y la clasificación de BlueXP.



== Regiones admitidas

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Consulte las regiones de Amazon admitidas."^]



== Obtener ayuda

Amazon FSX para ONTAP de NetApp es una solución de primera parte de AWS. Para preguntas o problemas de soporte técnico asociados con tu ONTAP sistema de archivos, infraestructura o cualquier solución que use este servicio, usa el Centro de soporte de tu consola de administración de AWS para abrir un caso de soporte con AWS. Seleccione el servicio "FSX for ONTAP" y la categoría adecuada. Proporcione la información restante necesaria para crear su caso de soporte de AWS.

Para preguntas generales sobre las soluciones y servicios de almacenamiento de BlueXP o BlueXP, puede comenzar con el chat en línea de BlueXP.

Para problemas relacionados con soporte técnico específicos de soluciones y servicios de almacenamiento de BlueXP o BlueXP, puedes abrir un ticket de soporte de NetApp mediante el número de serie de tu cuenta de BlueXP. Tendrá que hacerlo link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/support/task-support-registration.html["Registre su cuenta de BlueXP"^] para activar el soporte.
