---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager 
summary: Amazon FSx para NetApp ONTAP es un servicio totalmente gestionado que permite a los clientes iniciar y ejecutar sistemas de archivos con tecnología del sistema operativo de almacenamiento ONTAP de NetApp. 
---
= Obtenga más información sobre Amazon FSX para ONTAP de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX para ONTAP de NetApp"^] Es un servicio totalmente gestionado que permite a los clientes iniciar y ejecutar sistemas de archivos con tecnología del sistema operativo de almacenamiento NetApp ONTAP. FSX para ONTAP proporciona las mismas funciones, rendimiento y funcionalidades administrativas que los clientes de NetApp utilizan en las instalaciones, con la simplicidad, agilidad, seguridad y escalabilidad de un servicio de AWS nativo.



== Usando FSx para ONTAP en BlueXP 

Desde el lienzo de BlueXP , puedes crear y detectar entornos de trabajo de FSx para ONTAP, usar System Manager y otros servicios de BlueXP  y ver credenciales. Si en su lugar desea gestionar credenciales y cargas de trabajo que utilizan FSx para sistemas de archivos ONTAP, utilice https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Fábrica de cargas de trabajo BlueXP "^].

link:../use/task-creating-fsx-working-environment.html["Obtén más información sobre cómo usar FSx para ONTAP en BlueXP "^].



== Funciones

* No es necesario configurar ni gestionar dispositivos de almacenamiento, software o backups.
* Compatibilidad con https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html["S3"^] los protocolos CIFS, iSCSI, NFSv3, NFSv4.x y SMB v2,0 - v3,1.1.
* Capacidad de almacenamiento de datos prácticamente ilimitada y de bajo coste mediante el uso del nivel de almacenamiento a el que se accede con poca frecuencia (IA).
* Certificado para ejecutarse en aplicaciones sensibles a la latencia, incluido Oracle RAC.
* Opción de precios incluidos y de pago por uso.




== Características adicionales en BlueXP

* FSX para ONTAP es compatible cuando se utiliza BlueXP  en el modo _standard_, que aprovecha la capa SaaS de BlueXP  para ofrecer una funcionalidad completa.
+
Consulte link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Modos de implementación de BlueXP"^] si quiere más información.

* Uso link:https://docs.netapp.com/us-en/bluexp-family/["BlueXP"^] Además, con un conector en AWS, puedes crear y gestionar volúmenes, replicar datos e integrar FSx para ONTAP con los servicios de nube de NetApp, como la clasificación de BlueXP y la copia y sincronización de BlueXP.
* Con la tecnología impulsada por la inteligencia artificial (IA), la clasificación de BlueXP puede ayudarte a comprender el contexto de los datos e identificar los datos confidenciales que residen en tus cuentas de FSx para ONTAP. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Leer más"^].
* Con la copia y sincronización de BlueXP, podrá automatizar la migración de datos a cualquier destino en la nube u on-premises. https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["Leer más"^]




== Los conectores y enlaces desbloquean todas las características de FSX for ONTAP

Los conectores y los enlaces permiten la conectividad y las relaciones de confianza entre los entornos de trabajo de BlueXP  y Amazon FSx para NetApp ONTAP. Un conector BlueXP  es el software NetApp que se ejecuta en su red local o en la nube y un enlace usa AWS Lambda para ejecutar código NetApp. No necesitas un conector o un enlace para empezar a usar BlueXP  o crear entornos de trabajo de FSx para ONTAP, pero sí necesitas usar un conector o un enlace para aprovechar al máximo las funciones de FSx para ONTAP.

Obtenga más información sobre conectores y enlaces y cuándo debe usarlos:

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["Más información sobre conectores"^].
* https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Obtenga más información sobre los enlaces"^].




== Coste

Su cuenta FSX para ONTAP es mantenida por AWS y no por BlueXP. Consulte https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Guía de inicio de Amazon FSX para ONTAP de NetApp"^].

Hay un coste adicional asociado al uso del conector en AWS y a servicios de datos opcionales, como la copia y sincronización de BlueXP y la clasificación de BlueXP.



== Regiones admitidas

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Consulte las regiones de Amazon admitidas."^]



== Obtener ayuda

Amazon FSX para ONTAP de NetApp es una solución de primera parte de AWS. Para preguntas o problemas de soporte técnico asociados con su entorno de trabajo de FSx para ONTAP, infraestructura o cualquier solución que use este servicio, use el Centro de soporte de su consola de administración de AWS para abrir un caso de soporte con AWS. Selecciona el servicio «FSx para ONTAP» y la categoría adecuada. Proporcione la información restante necesaria para crear su caso de soporte de AWS.

Para preguntas generales sobre las soluciones y servicios de almacenamiento de BlueXP o BlueXP, puede comenzar con el chat en línea de BlueXP.

Para problemas de soporte técnico específicos de las soluciones y servicios de almacenamiento de BlueXP  o BlueXP , puede abrir un ticket de soporte de NetApp mediante el número de serie del nivel de organización de BlueXP . Deberá link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/support/task-support-registration.html["Registre su organización de BlueXP "^]activar el soporte.
